
[paths]
#cloud_path = "/Users/brett/Library/CloudStorage/GoogleDrive-blongworth@whoi.edu/Shared drives/locness/"
cloud_path = "C:/Users/CSL 2/Documents/LOCNESS_data/"
basename = "fake-data"
#db_path = "/Users/brett/Projects/locness/locness-datamanager/data/locness.db"
db_path= "C:/Users/CSL 2/Documents/LOCNESS_data/locness.db"

[resampling]
res_int = "2s" # resampling interval in time units, e.g., "2s" for 2 seconds
ph_ma_window = 120  # window in seconds for ph moving average
ph_freq = 0.1  # frequency in Hz for ph moving average
ph_k0 = 0.0  # k0 value for ph correction
ph_k2 = 0.0  # k2 value for ph correction

[output]
partition_hours = 12  # hours to partition the data for writing, not used yet

[synthetic_data]
num = 30 # number of samples to generate
freq = 0.5 # frequency in Hz for the generated data
continuous = true # whether to generate continuous data or not
