
[paths]
db_path= "C:/Users/CSL 2/Documents/LOCNESS_data/database/locness.db"
#db_path = "/Users/brett/Projects/locness/locness-datamanager/data/locness.db"
cloud_path = "G:/Shared drives/locness/synthetic_data/"
#cloud_path = "/Users/brett/Library/CloudStorage/GoogleDrive-blongworth@whoi.edu/Shared drives/locness/synthetic_data/:"
basename = "fake-data"
log_path = "C:/Users/CSL 2/Documents/LOCNESS_data/logs/"

[resampling]
poll_interval = 10 # frequency to poll and process raw data in seconds not used yet
res_int = "10s" # resampling interval in time units, e.g., "2s" for 2 seconds
ph_ma_window = 120  # window in seconds for ph moving average
ph_freq = 0.5  # frequency in Hz for ph moving average
# pH calibration coefficients
# mFET SB10
ph_k0 = -1.39469
ph_k2 = -0.00107

[output]
output_interval = 60  # frequency to write data to the resampled output in seconds not used yet
partition_hours = 6  # hours to partition the data for writing, not used yet
backup_interval = 24  # hours to backup the database, not used yet

[synthetic_data]
time = 60 # time in seconds of synthetic data to generate
num = 30 # number of samples to generate
freq = 0.5 # frequency in Hz for the generated data
continuous = true # whether to generate continuous data or not
