
[paths]
#db_path= "C:/Users/CSL 2/Documents/LOCNESS_data/database/locness.db"
db_path = "/Users/brett/Projects/locness/locness-datamanager/data/locness.db"
#parquet_path = "G:/Shared drives/locness/synthetic_data/locness.parquet"
parquet_path = "/Users/brett/Library/CloudStorage/GoogleDrive-blongworth@whoi.edu/Shared drives/locness/synthetic_data/locness.parquet"
# add csv_path to write summary csv
csv_path = "/Users/brett/Projects/locness/locness-datamanager/data/locness.csv"
#log_path = "C:/Users/CSL 2/Documents/LOCNESS_data/logs/"
log_path = "/Users/brett/Projects/locness/locness-datamanager/data/datamanager.log"
dynamodb_table = "locness-underway-summary"

[resample-db]
db_poll_interval = 10 # raw data polling interval in seconds
db_res_int = "2s" # resampling interval in time units, e.g., "2s" for 2 seconds
ph_ma_window = 120  # window in seconds for ph moving average
ph_freq = 0.5  # frequency in Hz for ph moving average
# pH calibration coefficients
# mFET SB10
ph_k0 = -1.39469
ph_k2 = -0.00107

[resample-output]
output_poll_interval = 60  # resampled output polling interval in seconds
output_res_int = "60s"  # resampling interval (time bucket size) in time units, e.g., "2s" for 2 seconds
partition_hours = 6  # hours to partition the data for writing

[db-backup]
backup_interval = 0.025  # database backup interval in hours
backup_path = "/Users/brett/Projects/locness/locness-datamanager/data/backup"  # path to backup the database

[synthetic_data]
time = 60 # time in seconds of synthetic data to generate
num = 30 # number of samples to generate
freq = 0.5 # frequency in Hz for the generated data
continuous = true # whether to generate continuous data or not
